![Credit card being held in hand](credit_card.jpg)

Commercial banks receive _a lot_ of applications for credit cards. Many of them get rejected for many reasons, like high loan balances, low income levels, or too many inquiries on an individual's credit report, for example. Manually analyzing these applications is mundane, error-prone, and time-consuming (and time is money!). Luckily, this task can be automated with the power of machine learning and pretty much every commercial bank does so nowadays. In this workbook, you will build an automatic credit card approval predictor using machine learning techniques, just like real banks do.

### The Data

The data is a small subset of the Credit Card Approval dataset from the UCI Machine Learning Repository showing the credit card applications a bank receives. This dataset has been loaded as a `pandas` DataFrame called `cc_apps`. The last column in the dataset is the target value.

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

# Load the dataset
cc_apps = pd.read_csv("cc_approvals.data", header=None) 
cc_apps.head()

  0      1      2  3  4  5  6     7  8  9   10 11   12 13
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  g    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  g  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  g  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  g    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  s    0  +

In [2]:
# Display unique values for each column in the DataFrame
unique_values = {col: cc_apps[col].unique() for col in cc_apps.columns}
unique_values

{0: array(['b', 'a', '?'], dtype=object),
 1: array(['30.83', '58.67', '24.50', '27.83', '20.17', '32.08', '33.17',
        '22.92', '54.42', '42.50', '22.08', '29.92', '38.25', '48.08',
        '45.83', '36.67', '28.25', '23.25', '21.83', '19.17', '25.00',
        '47.75', '27.42', '41.17', '15.83', '47.00', '56.58', '57.42',
        '42.08', '29.25', '42.00', '49.50', '36.75', '22.58', '27.25',
        '23.00', '27.75', '54.58', '34.17', '28.92', '29.67', '39.58',
        '56.42', '54.33', '41.00', '31.92', '41.50', '23.92', '25.75',
        '26.00', '37.42', '34.92', '34.25', '23.33', '23.17', '44.33',
        '35.17', '43.25', '56.75', '31.67', '23.42', '20.42', '26.67',
        '36.00', '25.50', '19.42', '32.33', '34.83', '38.58', '44.25',
        '44.83', '20.67', '34.08', '21.67', '21.50', '49.58', '27.67',
        '39.83', '?', '37.17', '25.67', '34.00', '49.00', '62.50', '31.42',
        '52.33', '28.75', '28.58', '22.50', '28.50', '37.50', '35.25',
        '18.67', '54.83', '40.92', '19.75', '29.17', '24.58', '33.75',
        '25.42', '37.75', '52.50', '57.83', '20.75', '39.92', '24.75',
        '44.17', '23.50', '47.67', '22.75', '34.42', '28.42', '67.75',
        '47.42', '36.25', '32.67', '48.58', '33.58', '18.83', '26.92',
        '31.25', '56.50', '43.00', '22.33', '32.83', '40.33', '30.50',
        '52.83', '46.67', '58.33', '37.33', '23.08', '32.75', '68.67',
        '28.00', '44.00', '25.08', '32.00', '60.58', '40.83', '19.33',
        '41.33', '56.00', '49.83', '22.67', '27.00', '26.08', '18.42',
        '21.25', '57.08', '22.42', '48.75', '40.00', '40.58', '28.67',
        '33.08', '21.33', '41.75', '34.50', '48.17', '27.58', '24.08',
        '24.83', '36.33', '35.42', '71.58', '39.50', '39.33', '24.33',
        '60.08', '55.92', '53.92', '18.92', '50.08', '65.42', '17.58',
        '18.08', '19.67', '25.17', '33.50', '58.42', '26.17', '42.83',
        '38.17', '20.50', '48.25', '28.33', '18.75', '18.50', '45.00',
        '40.25', '41.42', '17.83', '18.17', '20.00', '52.17', '50.75',
        '17.08', '18.33', '59.67', '18.00', '37.58', '30.67', '18.58',
        '16.25', '21.17', '17.67', '16.50', '29.50', '21.75', '18.25',
        '35.75', '16.08', '69.17', '32.92', '16.33', '22.17', '57.58',
        '15.92', '31.75', '19.00', '17.50', '33.67', '30.17', '33.25',
        '25.25', '34.75', '47.33', '39.08', '42.75', '38.92', '62.75',
        '32.25', '26.75', '63.33', '30.75', '16.00', '19.50', '32.42',
        '30.25', '26.83', '16.92', '24.42', '39.42', '23.58', '21.42',
        '33.00', '26.33', '26.25', '28.17', '20.83', '43.17', '56.83',
        '15.17', '29.83', '31.00', '51.92', '69.50', '19.58', '22.25',
        '38.42', '26.58', '35.00', '29.42', '49.17', '51.83', '58.58',
        '53.33', '27.17', '25.92', '30.58', '17.25', '27.33', '36.50',
        '29.75', '52.42', '36.17', '34.58', '21.92', '36.58', '31.08',
        '30.42', '21.08', '17.42', '39.17', '26.50', '17.33', '23.75',
        '34.67', '74.83', '45.33', '47.25', '24.17', '39.25', '39.00',
        '64.08', '31.33', '21.00', '13.75', '46.00', '20.25', '60.92',
        '30.00', '22.83', '45.17', '41.58', '55.75', '25.33', '31.83',
        '33.92', '24.92', '80.25', '30.08', '48.33', '76.75', '51.33',
        '41.92', '29.58', '32.17', '51.42', '42.17', '43.08', '59.50',
        '65.17', '20.33', '48.50', '28.08', '73.42', '51.58', '38.67',
        '46.08', '20.08', '42.25', '16.17', '47.83', '22.00', '38.33',
        '25.58', '21.58', '36.08', '38.75', '35.58', '31.58', '15.75',
        '17.92', '30.33', '47.17', '25.83', '50.25', '36.42'], dtype=object),
 2: array([ 0.   ,  4.46 ,  0.5  ,  1.54 ,  5.625,  4.   ,  1.04 , 11.585,
         4.915,  0.83 ,  1.835,  6.   ,  6.04 , 10.5  ,  4.415,  0.875,
         5.875,  0.25 ,  8.585, 11.25 ,  1.   ,  8.   , 14.5  ,  6.5  ,
         0.585, 13.   , 18.5  ,  8.5  , 14.79 ,  9.79 ,  7.585,  5.125,
        10.75 ,  1.5  ,  1.585, 11.75 ,  9.415,  9.17 , 15.   ,  1.415,
        13.915, 28.   ,  6.75 ,  2.04 ,  0.665,  2.5  ,  3.   , 11.625,
         4.5  , 12.25 , 16.165,  0.79 ,  0.835,  4.25 ,  0.375, 25.125,
         7.5  ,  5.   ,  7.   ,  5.29 ,  1.165,  9.75 , 19.   ,  3.5  ,
         0.625,  2.21 , 12.75 , 15.5  ,  1.375,  3.54 , 11.   ,  1.75 ,
        16.5  , 12.   ,  2.25 ,  0.75 , 12.5  ,  1.25 ,  1.125,  7.04 ,
        10.335,  6.21 ,  6.665,  9.   ,  5.5  ,  0.54 ,  2.75 ,  9.5  ,
        13.5  ,  3.75 , 16.   ,  0.29 ,  1.665,  7.54 ,  0.46 , 10.   ,
        11.5  ,  3.04 ,  2.   ,  0.08 ,  1.71 ,  3.25 ,  2.54 , 13.585,
         8.665,  9.25 ,  8.17 ,  2.335, 19.5  ,  5.665,  4.625,  0.205,
         0.96 ,  4.04 ,  5.04 ,  3.165,  7.625, 10.04 , 10.25 ,  2.125,
         9.335,  6.625,  2.71 ,  9.625, 12.54 ,  9.54 ,  8.46 , 13.75 ,
        21.   , 10.125, 25.085,  0.21 , 21.5  , 11.125, 11.045,  1.335,
         0.085,  1.21 ,  0.165,  5.71 ,  5.415, 12.625,  0.58 ,  0.415,
         2.415,  0.335,  3.125, 12.125,  2.875, 13.665, 26.335, 10.29 ,
         1.29 , 22.   ,  0.125,  1.085,  4.085,  4.71 ,  6.165,  4.585,
        11.46 , 14.585,  0.17 ,  1.625,  2.085,  5.085,  8.125,  2.835,
         1.79 ,  0.705,  2.165,  2.29 , 18.125,  3.085, 11.665,  4.125,
         1.08 , 13.335, 11.835,  4.79 ,  9.96 ,  7.08 , 25.21 ,  0.67 ,
         3.79 , 22.29 ,  3.335,  0.42 ,  1.46 ,  0.04 , 12.33 , 12.335,
         0.915, 14.   , 17.75 , 20.   ,  5.25 ,  4.165, 10.915,  4.75 ,
        10.415,  7.835,  0.71 ,  2.46 ,  9.585,  3.625,  2.665,  5.835,
        12.835, 10.665,  7.25 , 10.21 ,  3.29 , 10.085,  3.375]),
 3: array(['u', 'y', '?', 'l'], dtype=object),
 4: array(['g', 'p', '?', 'gg'], dtype=object),
 5: array(['w', 'q', 'm', 'r', 'cc', 'k', 'c', 'd', 'x', 'i', 'e', 'aa', 'ff',
        'j', '?'], dtype=object),
 6: array(['v', 'h', 'bb', 'ff', 'j', 'z', '?', 'o', 'dd', 'n'], dtype=object),
 7: array([ 1.25 ,  3.04 ,  1.5  ,  3.75 ,  1.71 ,  2.5  ,  6.5  ,  0.04 ,
         3.96 ,  3.165,  2.165,  4.335,  1.   ,  5.   ,  0.25 ,  0.96 ,
         3.17 ,  0.665,  0.75 ,  0.835,  7.875,  3.085,  0.5  ,  5.165,
        15.   ,  7.   ,  5.04 ,  7.96 ,  7.585,  0.415,  2.   ,  1.835,
        14.415,  4.5  ,  5.335,  8.625, 28.5  ,  2.625,  0.125,  6.04 ,
         3.5  ,  0.165,  0.875,  1.75 ,  0.   ,  7.415,  0.085,  5.75 ,
         6.   ,  3.   ,  1.585,  4.29 ,  1.54 ,  1.46 ,  1.625, 12.5  ,
        13.5  , 10.75 ,  0.375,  0.585,  0.455,  4.   ,  8.5  ,  9.46 ,
         2.25 , 10.   ,  0.795,  1.375,  1.29 , 11.5  ,  6.29 , 14.   ,
         0.335,  1.21 ,  7.375,  7.5  ,  3.25 , 13.   ,  5.5  ,  4.25 ,
         0.625,  5.085,  2.75 ,  2.375,  8.   ,  1.085,  2.54 ,  4.165,
         1.665, 11.   ,  9.   ,  1.335,  1.415,  1.96 ,  2.585,  5.125,
        15.5  ,  0.71 ,  5.665, 18.   ,  5.25 ,  8.665,  2.29 , 20.   ,
         2.46 , 13.875,  2.085,  4.58 ,  2.71 ,  2.04 ,  0.29 ,  4.75 ,
         0.46 ,  0.21 ,  0.54 ,  3.335,  2.335,  1.165,  2.415,  2.79 ,
         4.625,  1.04 ,  6.75 ,  1.875, 16.   , 12.75 ,  5.375,  2.125,
        17.5  ,  3.125,  0.79 ,  8.29 ]),
 8: array(['t', 'f'], dtype=object),
 9: array(['t', 'f'], dtype=object),
 10: array([ 1,  6,  0,  5,  7, 10,  3, 17,  2,  9,  8, 15, 11, 12, 40, 23,  4,
        20, 67, 14, 16, 13, 19]),
 11: array(['g', 's', 'p'], dtype=object),
 12: array([     0,    560,    824,      3,  31285,   1349,    314,   1442,
           200,   2690,    245,   1208,   1260,     11,  10000,   5000,
          4000,     35,    713,    551,    500,    300,    221,   2283,
           100,     15,    284,   1236,   5800,    730,    400,  50000,
           456,  15108,   2954,      2,     20,     27,    225,      1,
            38,      5,    130,    147,    210,  11202,   1332,     50,
           258,    567,   1000,   2510,    809,    610,    150,  51100,
           367,    600,    247,    375,    278,    827,   2072,    582,
          2300,   3065,   2200,      6,   1602,   2184,   3376,   2000,
          7544,  10561,    837,  11177,    639,   2028,   1065,    540,
           158,  15000,   3000,   3257,   1655,   1430,      7,    790,
           396,    678,   1187,   6590,    168,   1270,   1210,    742,
          8851,   7059,   1704,    857,   6700,   2503,   9800,    196,
            14,  26726,  18027,     99,    444,   1200,   2010,     13,
           120,     32,    722,     40,    484,    204,     98,   5552,
           105,   2803,    126,      4,     21,    173,     10,     25,
            42, 100000,    113,      8,     44,   2732,    179,     16,
          1062,    251,    228,     67,     12,    122,   4208,   1300,
           112,   1110,   1004,    286,   4500,   1212,    195,     87,
            17,    184,    140,     18,    146,     22,     55,     70,
            60,   1058,    769,   5200,     19,    316,    350,   3552,
           687,   1950,     53,     41,     33,     80,    351,   2100,
           475,    892,   4607,   2206,   5860,     28,   1391,   2279,
           591,    960,    690,    234,    800,    990,   2197,     90,
           340,    347,    327,   4071,    109,   1249,    134,   1344,
           321,    948,   2079,   2384,    458,   5298,    162,   1583,
            58,     59,   1400,   1465,   8000,   4700,   1097,   3290,
         13212,   5777,   5124,     23,   4159,    918,    768,    283,
           108,      9,     68,    587,    141,    501,    160,    390,
           154,    117,    246,    237,    364,    537,    394,    750]),
 13: array(['+', '-'], dtype=object)}

In [3]:
# Display the number of null values in the dataset
cc_apps.isnull().sum().sum()

0

In [4]:
# Calculate the total number of NaN values in the DataFrame
cc_apps.isna().sum().sum()

0

In [5]:
cc_apps.dtypes

0      object
1      object
2     float64
3      object
4      object
5      object
6      object
7     float64
8      object
9      object
10      int64
11     object
12      int64
13     object
dtype: object

In [6]:
# Split cc_apps into X (features) and y (target)
y = cc_apps[13]
X = cc_apps.drop(13, axis=1)
X = pd.get_dummies(X, columns=[0,1,3,4,5,6,8,9,11], drop_first=True)
y = pd.get_dummies(y, drop_first=True)
X

          2     7  10   12  0_a  0_b  ...  6_v  6_z  8_t  9_t  11_p  11_s
0     0.000  1.25   1    0    0    1  ...    1    0    1    1     0     0
1     4.460  3.04   6  560    1    0  ...    0    0    1    1     0     0
2     0.500  1.50   0  824    1    0  ...    0    0    1    0     0     0
3     1.540  3.75   5    3    0    1  ...    1    0    1    1     0     0
4     5.625  1.71   0    0    0    1  ...    1    0    1    0     0     1
..      ...   ...  ..  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...
685  10.085  1.25   0    0    0    1  ...    0    0    0    0     0     0
686   0.750  2.00   2  394    1    0  ...    1    0    0    1     0     0
687  13.500  2.00   1    1    1    0  ...    0    0    0    1     0     0
688   0.205  0.04   0  750    0    1  ...    1    0    0    0     0     0
689   3.375  8.29   0    0    0    1  ...    0    0    0    0     0     0

[690 rows x 388 columns]

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 42)

In [11]:
y_test

     -
286  1
511  0
257  1
336  1
318  0
..  ..
333  1
507  0
24   0
158  0
518  0

[138 rows x 1 columns]

In [57]:
scaler = StandardScaler()

# Use double brackets to select columns by index positions
cols = [2, 7, 10, 12]
X_train_scaled = scaler.fit_transform(X_train[cols])
X_test_scaled = scaler.transform(X_test[cols])

In [58]:
# Initialize the Logistic Regression model
logreg = LogisticRegression(penalty = "elasticnet", solver = "saga", l1_ratio=0.99, max_iter=200, random_state=42, tol = 0.01)

# Fit the model on the scaled training data
logreg.fit(X_train_scaled, y_train.values.ravel())

# Generate predictions on the test set
y_pred = logreg.predict(X_test_scaled)

y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1], dtype=uint8)

In [59]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.7587719298245614

In [ ]:
help me use gridsearchcv to generate for me a